### ISSUE TITLE
ConPTY support

### ISSUE THREAD

**Issue by dumblob** [robhagemans/ansipipe#1]
Any plans to support [ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/ ) API?

At least as compile-time option after choosing a "minimum supported platform" (in case of ConPTY probably Windows 10). But better in runtime, so that nobody needs to care about it :wink:.

**Comment by robhagemans** [comment]
Hi, I've no plans to further develop ansipipe, sorry. It was always a niche; the main (only?) "user" was my https://github.com/robhagemans/pcbasic application, but I've migrated that to using the Window API directly to make deployment easier. Now that Win10 supports ANSI natively I'm not sure there is much reason for using this wrapper anymore.

**Comment by dumblob** [comment]
Oh, thanks for the information. I consider ansipipe pretty mature and stable. Any issues you'd know about?

**Comment by robhagemans** [comment]
No, haven't really run into issues, the main reason I stopped using it was that it allowed me to move my other project to Python-only, which made deployment a lot simpler. It's a fairly simple codebase and mostly made up of other people's work I borrowed from stable projects.

**Comment by dumblob** [comment]
Makes sense, thanks for confirmation. I'm closing this for now then.
